version: "3.8"

services:
  app-dl:
    container_name: app-dl
    build: ./php
    volumes:
      - ./:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./log:/var/log

  web-dl:
    container_name: web-dl
    build:
      context: ./php
    ports:
        - '8080:80'
    volumes:
      - ./src:/var/www/docker-laravel
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db-dl

  # .envファイルの「DB_HOST」とサービス名を合わせる
  db-dl:
    platform: linux/x86_64
    image: mysql:latest
    container_name: db-dl
    environment:
      MYSQL_ROOT_PASSWORD: root
      # .envファイルの「DB_DATABASE」とMYSQL_DATABASEを合わせる
      MYSQL_DATABASE: recip
      TZ: "Asia/Tokyo"
      # 文字コード指定
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin-dl:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-dl
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db-dl
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db-dl
    ports:
      - 8580:80
    volumes:
      - /sessions

  mailcatcher-dl:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
